version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
      tag: '10.16.3'
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: sudo npm install -g serverless
            - run: sls invoke local -f hello --stage stage --S3BucketName interview-bucket-asm --DestFile test.txt
            - run: sls deploy --stage stage --S3BucketName interview-bucket-asm --DestFile test.txt
            
workflows:
    version: 2
    build-and-test:
      jobs:
        - build-and-test:
            filters:
              branches:
                only: master

