version: 2.1
jobs:
  build:
     docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: 
                 name: update-npm
                 command: 'sudo npm install -g npm@latest'
            - run: npm install
            - run: npm test
workflows:
    build-and-test:
      jobs:
        - build-and-test