version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
      tag: '10.16.3'
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: sudo find / -name TESTFILE.txt
            - run: npm install
            - run: which npm && which node
            - run: npm --version && node --version
workflows:
    build-and-test:
      jobs:
        - build-and-test
