version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
      tag: '10.16.3'
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: 
                 name: Install serverless
                 command: sudo npm install -g serverless
      - localtest:
          steps:
            - run: 
                 name: Run local invocation to ensure correct running
                 command: sls invoke local -f helloWorld --stage stage --S3BucketName interview-bucket-asm --DestFile test.txt
      - deploy:
          steps:
            - run: 
                 name: Deploy to live
                 command: sls deploy --stage stage --S3BucketName interview-bucket-asm --DestFile test.txt
            
workflows:
    version: 2
    build-and-test:
      jobs:
        - build-and-test:
            filters:
              branches:
                only: master

