version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
      tag: '10.16.3'
    steps:
      - checkout
      - awscli-setup:
          steps:
            - run:
                 name: update apt-get
                 command: sudo apt-get update && sudo apt-get install awscli
      - node/with-cache:
          steps:
            - run: 
                 name: Install serverless
                 command: sudo npm install -g serverless
            - run: 
                 name: Run local invocation to ensure correct running
                 command: sls invoke local -f helloWorld 
            - run: 
                 name: Deploy to live
                 command: sls deploy 
            
workflows:
    version: 2
    build-and-test:
      jobs:
        - build-and-test:
            filters:
              branches:
                only: master

